### ISSUE TITLE
database: return cancelled but running jobs in get_schedule()

### ISSUE THREAD

**Issue by ammen99** [DistributedTaskScheduling/JobAdder#167]
Right now, the scheduler tries to get the schedule from the database, but looking at the code, this doesn't include cancelled-but-running jobs (these can be detected by looking at their assigned machine).

Also, the scheduler does not take these jobs into account.

I'll have to look into the scheduler part, @nikolatzotchev can you fix the database part?

**Comment by nikolatzotchev** [comment]
I could, is it really important for your tests? I'm asking just to know should I check it before doing my job.

**Comment by ammen99** [comment]
You can add it in unit tests. If you see the docstring of the database, it says it should return ... types, and also these that have an assigned work machine.

It will be important for the tests since without this, a running job cannot be cancelled (its status will be set to cancelled, but this will never be forwarded to the dispatcher).
