### ISSUE TITLE
CLIHandler class diagrams

### ISSUE THREAD

**Issue by M1keReck** [DistributedTaskScheduling/JobAdder#17]

**Comment by JohannesGaessler** [comment]
According to the plan we made before the break @ammen99 is assigned for this issue.
Will you be able to do it on time?

**Comment by ammen99** [comment]
Somehow I have missed this issue. I'll do it right away.

**Comment by ammen99** [comment]
@JohannesGaessler are you sure this was my assignment? I thought my new tasks were the notifier and web api, not CLI handler ...

**Comment by JohannesGaessler** [comment]
That's at least how I've written it down before the break.
I'll just do it myself; it's not much that is to be done.
