### ISSUE TITLE
setup.py doesn't include Python dependencies

### ISSUE THREAD

**Issue by JohannesGaessler** [DistributedTaskScheduling/JobAdder#191]
Currently executing install.sh doesn't install necessary Python packages like yaml.

**Comment by ammen99** [comment]
I do not think it is a good idea to do that. Python packages are best installed via the package manager if they are recent enough. Why not just list them?

**Comment by JohannesGaessler** [comment]
I think I phrased this issue poorly.
What I meant is that after executing the install script Python dependencies should be installed.
I am planning to do this by listing the dependencies in setup.py and leaving the rest to pip.
