### ISSUE TITLE
Email Notifier and Web API

### ISSUE THREAD

**Issue by ammen99** [DistributedTaskScheduling/JobAdder#23]
I think I was assigned these two in our last meeting.

Two questions:

1. Do we store a list of emails for each user, or do we store an email for each job?
2. Do we need HTTPS for the server or plain HTTP?

**Comment by JohannesGaessler** [comment]
1. I think email addresses should be stored per job because we do not have a database of users, only a database of jobs, right?
2. I think HTTP is enough. We are after all not making a website that is visible to the public internet but an interface that is accessed from within a private network.

**Comment by nikolatzotchev** [comment]
It also shouldn't be to difficult to change it from HTTP to HTTPS later.
