### ISSUE TITLE
Decide on coding style and add CI

### ISSUE THREAD

**Issue by ammen99** [DistributedTaskScheduling/JobAdder#3]
We really should have a consistent style. My proposal is to use the official Python styleguide: [PEP 8](https://www.python.org/dev/peps/pep-0008/).There are also good tools which check this, for example flake8.

Another thing is checking the type hints consistency with MyPy.

Anything else we want to check?

**Comment by nikolatzotchev** [comment]
maybe also [PEP 257](https://www.python.org/dev/peps/pep-0257/), for docstring, But it is most probably said in PEP 8.

**Comment by JohannesGaessler** [comment]
Should we use " or ' for strings?

**Comment by ammen99** [comment]
@nikolatzotchev Is it PEP 257 compatible with Doxygen?



> Should we use " or ' for strings?
> I normally use ' because I think they're easier to type.

I am fine with both.

**Comment by nikolatzotchev** [comment]
I think so.
