### ISSUE TITLE
common is importing from server

### ISSUE THREAD

**Issue by JohannesGaessler** [DistributedTaskScheduling/JobAdder#30]
I added an argument of type `ja.common.database.database.ServerDatabase` to the execute method of `ja.common.message.server.ServerCommand`.
As a consequence common is now importing from server.
We had agreed that user, server, and worker should only import from common.
Should we allow that common also (rarely) imports from user, server, or worker?
Otherwise we would have to move the entire database into common.

**Comment by ammen99** [comment]
I think that the ServerCommands as a whole belong to either the server or the user package. The database IMO clearly belongs in the server.

**Comment by JohannesGaessler** [comment]
As discussed in the meeting this is not a problem for testing because common only depends on the interface of server, not the implementation.
