### ISSUE TITLE
User -> Server messages

### ISSUE THREAD

**Issue by ammen99** [DistributedTaskScheduling/JobAdder#69]
Messages which the UserClient sends to the Server.
They operate on the ServerDatabase.

from `ja.user.message`:

- [ ] add

- [ ] cancel

- [ ] query

**Comment by M1keReck** [comment]
Being resolved in #58

**Comment by nikolatzotchev** [comment]
I don't think this is resolved I just moved the code from the configs to there, for re-use of code.
