### ISSUE TITLE
Response classes should be unified

### ISSUE THREAD

**Issue by JohannesGaessler** [DistributedTaskScheduling/JobAdder#95]
As discussed in the meting, I think we should have only a single Response class instead of Response, ServerResponse, and WorkerResponse.
Since we currently have a lot of PRs open this change should wait until we have a lower amount of PRs open.

**Comment by nikolatzotchev** [comment]
I don't think this is entirely fixed yet.

**Comment by JohannesGaessler** [comment]
It isn't.
I was considering doing it in one of my PRs but that would have messes with all of the other PRs because I would have changed interfaces.
